# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../InitDirect3D/Includes/Camera.h \
    ../InitDirect3D/Includes/D3DApp.h \
    ../InitDirect3D/Includes/D3DUtils.h \
    ../InitDirect3D/Includes/Direct3DRenderer.h \
    ../InitDirect3D/Includes/FBXImporter.h \
    ../InitDirect3D/Includes/GameTimer.h \
    ../InitDirect3D/Includes/Geometry.h \
    ../InitDirect3D/Includes/GeometryGenerator.h \
    ../InitDirect3D/Includes/IRenderable.h \
    ../InitDirect3D/Includes/Log.h \
    ../InitDirect3D/Includes/MathHelper.h \
    ../InitDirect3D/Includes/Shader.h \
    ../InitDirect3D/Includes/SharedParameters.h \
    ../InitDirect3D/Includes/stdafx.h \
    ./stdafx.h \
    ./d3drenderingwidget.h \
    ./editor.h
SOURCES += ../InitDirect3D/Sources/Camera.cpp \
    ../InitDirect3D/Sources/D3DApp.cpp \
    ../InitDirect3D/Sources/D3DUtils.cpp \
    ../InitDirect3D/Sources/Direct3DRenderer.cpp \
    ../InitDirect3D/Sources/FBXImporter.cpp \
    ../InitDirect3D/Sources/GameTimer.cpp \
    ../InitDirect3D/Sources/Geometry.cpp \
    ../InitDirect3D/Sources/GeometryGenerator.cpp \
    ../InitDirect3D/Sources/IRenderable.cpp \
    ../InitDirect3D/Sources/Log.cpp \
    ../InitDirect3D/Sources/MathHelper.cpp \
    ../InitDirect3D/Sources/Shader.cpp \
    ../InitDirect3D/Sources/SharedParameters.cpp \
    ./d3drenderingwidget.cpp \
    ./editor.cpp \
    ./main.cpp \
    ./stdafx.cpp
FORMS += ./editor.ui \
    ./d3drenderingwidget.ui
RESOURCES += editor.qrc
